"""
Step 10: Subtitle and Export Generator
Converts transcript segments into standard SRT, WebVTT, Plain Text, and JSON subtitle formats.
"""

import json
import logging
from typing import List, Dict, Any
from speechsight.core.models import TranscriptSegment, TranscriptResult

logger = logging.getLogger("speechsight.pipeline.subtitles")


def format_timestamp_srt(seconds: float) -> str:
    """Formats float seconds into SRT timestamp: HH:MM:SS,mmm"""
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int(round((seconds - int(seconds)) * 1000))
    return f"{hrs:02d}:{mins:02d}:{secs:02d},{millis:03d}"


def format_timestamp_vtt(seconds: float) -> str:
    """Formats float seconds into WebVTT timestamp: HH:MM:SS.mmm"""
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int(round((seconds - int(seconds)) * 1000))
    return f"{hrs:02d}:{mins:02d}:{secs:02d}.{millis:03d}"


def format_timestamp_short(seconds: float) -> str:
    """Formats float seconds into MM:SS"""
    mins = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{mins:02d}:{secs:02d}"


class SubtitleGenerator:
    @staticmethod
    def to_srt(segments: List[TranscriptSegment], include_speaker: bool = True) -> str:
        """Generates standard SubRip (.srt) subtitle string."""
        lines = []
        for idx, seg in enumerate(segments, 1):
            start_str = format_timestamp_srt(seg.start_time)
            end_str = format_timestamp_srt(seg.end_time)
            speaker_prefix = f"[{seg.speaker}] " if include_speaker and seg.speaker else ""
            lines.append(f"{idx}")
            lines.append(f"{start_str} --> {end_str}")
            lines.append(f"{speaker_prefix}{seg.text}")
            lines.append("")  # Blank line separator
        return "\n".join(lines).strip()

    @staticmethod
    def to_vtt(segments: List[TranscriptSegment], include_speaker: bool = True) -> str:
        """Generates standard WebVTT (.vtt) subtitle string."""
        lines = ["WEBVTT - Generated by SpeechSight AI", ""]
        for idx, seg in enumerate(segments, 1):
            start_str = format_timestamp_vtt(seg.start_time)
            end_str = format_timestamp_vtt(seg.end_time)
            lines.append(f"{idx}")
            lines.append(f"{start_str} --> {end_str}")
            if include_speaker and seg.speaker:
                lines.append(f"<v {seg.speaker}>{seg.text}")
            else:
                lines.append(seg.text)
            lines.append("")
        return "\n".join(lines).strip()

    @staticmethod
    def to_plain_text(segments: List[TranscriptSegment], include_timestamps: bool = True) -> str:
        """Generates human-readable plain text transcript."""
        lines = []
        for seg in segments:
            if include_timestamps:
                ts = f"[{format_timestamp_short(seg.start_time)} - {format_timestamp_short(seg.end_time)}]"
                lines.append(f"{ts} {seg.speaker}: {seg.text}")
            else:
                lines.append(f"{seg.speaker}: {seg.text}")
        return "\n".join(lines)

    @staticmethod
    def to_json(result: TranscriptResult) -> str:
        """Serializes result into standard SpeechSight JSON format."""
        return result.model_dump_json(indent=2)
